version: "3.8"

volumes:
  database-data:
  logs:

networks:
  lunareclipse:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lunareclipse-backend
    restart: always
    ports:
      - 3001:3001
    links:
      - database
    networks:
      - lunareclipse

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: lunareclipse-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - lunareclipse

  database:
    image: "mariadb:${MARIADB_VERSION}"
    container_name: lunareclipse-database
    restart: always
    env_file:
      - path: ./.env
        required: true
    volumes:
      - "database-data:${MARIADB_DATA_DIR}"
      - "logs:${MARIADB_LOG_DIR}"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - lunareclipse
    ports:
      - 5010:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 5011:8080
